package com.asm.entity;
// Generated Jul 21, 2023, 11:15:56 AM by Hibernate Tools 4.3.6.Final

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;

/**
 * Category generated by hbm2java
 */
@Entity
@Table(name = "category", schema = "dbo", catalog = "DBAsmJv6")
public class Category implements java.io.Serializable {

	private String idCategory;
	private Serializable name;
	private Set<Product> products = new HashSet<Product>(0);

	public Category() {
	}

	public Category(String idCategory) {
		this.idCategory = idCategory;
	}

	public Category(String idCategory, Serializable name, Set<Product> products) {
		this.idCategory = idCategory;
		this.name = name;
		this.products = products;
	}

	@Id

	@Column(name = "idCategory", unique = true, nullable = false, length = 10)
	public String getIdCategory() {
		return this.idCategory;
	}

	public void setIdCategory(String idCategory) {
		this.idCategory = idCategory;
	}

	@Column(name = "name")
	public Serializable getName() {
		return this.name;
	}

	public void setName(Serializable name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "category")
	public Set<Product> getProducts() {
		return this.products;
	}

	public void setProducts(Set<Product> products) {
		this.products = products;
	}

}
