package com.asm.entity;
// Generated Jul 21, 2023, 11:15:56 AM by Hibernate Tools 4.3.6.Final

import java.io.Serializable;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * Image generated by hbm2java
 */
@Entity
@Table(name = "image", schema = "dbo", catalog = "DBAsmJv6")
public class Image implements java.io.Serializable {

	private String idImage;
	private Product product;
	private Serializable url;

	public Image() {
	}

	public Image(String idImage) {
		this.idImage = idImage;
	}

	public Image(String idImage, Product product, Serializable url) {
		this.idImage = idImage;
		this.product = product;
		this.url = url;
	}

	@Id

	@Column(name = "idImage", unique = true, nullable = false, length = 50)
	public String getIdImage() {
		return this.idImage;
	}

	public void setIdImage(String idImage) {
		this.idImage = idImage;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idProduct")
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@Column(name = "URL")
	public Serializable getUrl() {
		return this.url;
	}

	public void setUrl(Serializable url) {
		this.url = url;
	}

}
