package com.asm.entity;
// Generated Jul 21, 2023, 11:15:56 AM by Hibernate Tools 4.3.6.Final

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * InvoiceDetails generated by hbm2java
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
@Entity
@Table(name = "invoiceDetails", schema = "dbo", catalog = "DBAsmJv6")
public class InvoiceDetails implements java.io.Serializable {
	@Id

	@Column(name = "idInvoiceDetails")
	private String idInvoiceDetails;
	@ManyToOne
	@JoinColumn(name = "idInvoice")
	private Invoice invoice;


	@ManyToOne
	@JoinColumn(name = "idProduct")
	private Product product;
	@Column(name = "Price")
	private Double price;
	@Column(name = "quantity")
	private Integer quantity;










}
