package com.asm.entity;
// Generated Jul 21, 2023, 11:15:56 AM by Hibernate Tools 4.3.6.Final

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * Invoice generated by hbm2java
 */
@Entity
@Table(name = "invoice", schema = "dbo", catalog = "DBAsmJv6")
public class Invoice implements java.io.Serializable {

	private String idInvoice;
	private Users users;
	private Serializable phone;
	private Serializable address;
	private Date dateCreate;
	private Boolean status;
	private Set<InvoiceDetails> invoiceDetailses = new HashSet<InvoiceDetails>(0);

	public Invoice() {
	}

	public Invoice(String idInvoice) {
		this.idInvoice = idInvoice;
	}

	public Invoice(String idInvoice, Users users, Serializable phone, Serializable address, Date dateCreate,
			Boolean status, Set<InvoiceDetails> invoiceDetailses) {
		this.idInvoice = idInvoice;
		this.users = users;
		this.phone = phone;
		this.address = address;
		this.dateCreate = dateCreate;
		this.status = status;
		this.invoiceDetailses = invoiceDetailses;
	}

	@Id

	@Column(name = "idInvoice", unique = true, nullable = false, length = 10)
	public String getIdInvoice() {
		return this.idInvoice;
	}

	public void setIdInvoice(String idInvoice) {
		this.idInvoice = idInvoice;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idUser")
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@Column(name = "phone")
	public Serializable getPhone() {
		return this.phone;
	}

	public void setPhone(Serializable phone) {
		this.phone = phone;
	}

	@Column(name = "address")
	public Serializable getAddress() {
		return this.address;
	}

	public void setAddress(Serializable address) {
		this.address = address;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dateCreate", length = 10)
	public Date getDateCreate() {
		return this.dateCreate;
	}

	public void setDateCreate(Date dateCreate) {
		this.dateCreate = dateCreate;
	}

	@Column(name = "status")
	public Boolean getStatus() {
		return this.status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "invoice")
	public Set<InvoiceDetails> getInvoiceDetailses() {
		return this.invoiceDetailses;
	}

	public void setInvoiceDetailses(Set<InvoiceDetails> invoiceDetailses) {
		this.invoiceDetailses = invoiceDetailses;
	}

}
