package com.asm.entity;
// Generated Jul 21, 2023, 11:15:56 AM by Hibernate Tools 4.3.6.Final

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * InvoiceDetails generated by hbm2java
 */
@Entity
@Table(name = "invoiceDetails", schema = "dbo", catalog = "DBAsmJv6")
public class InvoiceDetails implements java.io.Serializable {

	private String idInvoiceDetails;
	private Invoice invoice;
	private Product product;
	private Double price;
	private Integer quantity;

	public InvoiceDetails() {
	}

	public InvoiceDetails(String idInvoiceDetails) {
		this.idInvoiceDetails = idInvoiceDetails;
	}

	public InvoiceDetails(String idInvoiceDetails, Invoice invoice, Product product, Double price, Integer quantity) {
		this.idInvoiceDetails = idInvoiceDetails;
		this.invoice = invoice;
		this.product = product;
		this.price = price;
		this.quantity = quantity;
	}

	@Id

	@Column(name = "idInvoiceDetails", unique = true, nullable = false, length = 10)
	public String getIdInvoiceDetails() {
		return this.idInvoiceDetails;
	}

	public void setIdInvoiceDetails(String idInvoiceDetails) {
		this.idInvoiceDetails = idInvoiceDetails;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idInvoice")
	public Invoice getInvoice() {
		return this.invoice;
	}

	public void setInvoice(Invoice invoice) {
		this.invoice = invoice;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idProduct")
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@Column(name = "Price", precision = 53, scale = 0)
	public Double getPrice() {
		return this.price;
	}

	public void setPrice(Double price) {
		this.price = price;
	}

	@Column(name = "quantity")
	public Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

}
