package com.asm.entity;
// Generated Jul 21, 2023, 11:15:56 AM by Hibernate Tools 4.3.6.Final

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name = "product", schema = "dbo", catalog = "DBAsmJv6")
public class Product implements java.io.Serializable {

	private String idProduct;
	private Category category;
	private Producer producer;
	private Serializable name;
	private Double price;
	private Integer quantity;
	private Boolean status;
	private Set<SpecificationDetails> specificationDetailses = new HashSet<SpecificationDetails>(0);
	private Set<InvoiceDetails> invoiceDetailses = new HashSet<InvoiceDetails>(0);
	private Set<Image> images = new HashSet<Image>(0);

	public Product() {
	}

	public Product(String idProduct) {
		this.idProduct = idProduct;
	}

	public Product(String idProduct, Category category, Producer producer, Serializable name, Double price,
			Integer quantity, Boolean status, Set<SpecificationDetails> specificationDetailses,
			Set<InvoiceDetails> invoiceDetailses, Set<Image> images) {
		this.idProduct = idProduct;
		this.category = category;
		this.producer = producer;
		this.name = name;
		this.price = price;
		this.quantity = quantity;
		this.status = status;
		this.specificationDetailses = specificationDetailses;
		this.invoiceDetailses = invoiceDetailses;
		this.images = images;
	}

	@Id

	@Column(name = "idProduct", unique = true, nullable = false, length = 10)
	public String getIdProduct() {
		return this.idProduct;
	}

	public void setIdProduct(String idProduct) {
		this.idProduct = idProduct;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "category")
	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "producer")
	public Producer getProducer() {
		return this.producer;
	}

	public void setProducer(Producer producer) {
		this.producer = producer;
	}

	@Column(name = "name")
	public Serializable getName() {
		return this.name;
	}

	public void setName(Serializable name) {
		this.name = name;
	}

	@Column(name = "price", precision = 53, scale = 0)
	public Double getPrice() {
		return this.price;
	}

	public void setPrice(Double price) {
		this.price = price;
	}

	@Column(name = "quantity")
	public Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	@Column(name = "status")
	public Boolean getStatus() {
		return this.status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
	public Set<SpecificationDetails> getSpecificationDetailses() {
		return this.specificationDetailses;
	}

	public void setSpecificationDetailses(Set<SpecificationDetails> specificationDetailses) {
		this.specificationDetailses = specificationDetailses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
	public Set<InvoiceDetails> getInvoiceDetailses() {
		return this.invoiceDetailses;
	}

	public void setInvoiceDetailses(Set<InvoiceDetails> invoiceDetailses) {
		this.invoiceDetailses = invoiceDetailses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
	public Set<Image> getImages() {
		return this.images;
	}

	public void setImages(Set<Image> images) {
		this.images = images;
	}

}
