package com.asm.entity;
// Generated Jul 21, 2023, 11:15:56 AM by Hibernate Tools 4.3.6.Final

import jakarta.persistence.Column;
import jakarta.persistence.Embeddable;

/**
 * SpecificationDetailsId generated by hbm2java
 */
@Embeddable
public class SpecificationDetailsId implements java.io.Serializable {

	private String idSpecificationDetails;
	private String idProduct;
	private String idSpecification;

	public SpecificationDetailsId() {
	}

	public SpecificationDetailsId(String idSpecificationDetails, String idProduct, String idSpecification) {
		this.idSpecificationDetails = idSpecificationDetails;
		this.idProduct = idProduct;
		this.idSpecification = idSpecification;
	}

	@Column(name = "idSpecificationDetails", nullable = false, length = 10)
	public String getIdSpecificationDetails() {
		return this.idSpecificationDetails;
	}

	public void setIdSpecificationDetails(String idSpecificationDetails) {
		this.idSpecificationDetails = idSpecificationDetails;
	}

	@Column(name = "idProduct", nullable = false, length = 10)
	public String getIdProduct() {
		return this.idProduct;
	}

	public void setIdProduct(String idProduct) {
		this.idProduct = idProduct;
	}

	@Column(name = "idSpecification", nullable = false, length = 10)
	public String getIdSpecification() {
		return this.idSpecification;
	}

	public void setIdSpecification(String idSpecification) {
		this.idSpecification = idSpecification;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SpecificationDetailsId))
			return false;
		SpecificationDetailsId castOther = (SpecificationDetailsId) other;

		return ((this.getIdSpecificationDetails() == castOther.getIdSpecificationDetails())
				|| (this.getIdSpecificationDetails() != null && castOther.getIdSpecificationDetails() != null
						&& this.getIdSpecificationDetails().equals(castOther.getIdSpecificationDetails())))
				&& ((this.getIdProduct() == castOther.getIdProduct()) || (this.getIdProduct() != null
						&& castOther.getIdProduct() != null && this.getIdProduct().equals(castOther.getIdProduct())))
				&& ((this.getIdSpecification() == castOther.getIdSpecification())
						|| (this.getIdSpecification() != null && castOther.getIdSpecification() != null
								&& this.getIdSpecification().equals(castOther.getIdSpecification())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIdSpecificationDetails() == null ? 0 : this.getIdSpecificationDetails().hashCode());
		result = 37 * result + (getIdProduct() == null ? 0 : this.getIdProduct().hashCode());
		result = 37 * result + (getIdSpecification() == null ? 0 : this.getIdSpecification().hashCode());
		return result;
	}

}
