package com.asm.entity;
// Generated Jul 21, 2023, 11:15:56 AM by Hibernate Tools 4.3.6.Final

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;

/**
 * Specification generated by hbm2java
 */
@Entity
@Table(name = "specification", schema = "dbo", catalog = "DBAsmJv6")
public class Specification implements java.io.Serializable {

	private String idSpecification;
	private Serializable keys;
	private Serializable value;
	private Set<SpecificationDetails> specificationDetailses = new HashSet<SpecificationDetails>(0);

	public Specification() {
	}

	public Specification(String idSpecification) {
		this.idSpecification = idSpecification;
	}

	public Specification(String idSpecification, Serializable keys, Serializable value,
			Set<SpecificationDetails> specificationDetailses) {
		this.idSpecification = idSpecification;
		this.keys = keys;
		this.value = value;
		this.specificationDetailses = specificationDetailses;
	}

	@Id

	@Column(name = "idSpecification", unique = true, nullable = false, length = 10)
	public String getIdSpecification() {
		return this.idSpecification;
	}

	public void setIdSpecification(String idSpecification) {
		this.idSpecification = idSpecification;
	}

	@Column(name = "keys")
	public Serializable getKeys() {
		return this.keys;
	}

	public void setKeys(Serializable keys) {
		this.keys = keys;
	}

	@Column(name = "value")
	public Serializable getValue() {
		return this.value;
	}

	public void setValue(Serializable value) {
		this.value = value;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "specification")
	public Set<SpecificationDetails> getSpecificationDetailses() {
		return this.specificationDetailses;
	}

	public void setSpecificationDetailses(Set<SpecificationDetails> specificationDetailses) {
		this.specificationDetailses = specificationDetailses;
	}

}
