package com.asm.entity;
// Generated Jul 21, 2023, 11:15:56 AM by Hibernate Tools 4.3.6.Final

import java.io.Serializable;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonIgnore;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Specification generated by hbm2java
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
@Entity
@Table(name = "specification")
public class Specification {
	@Id
	@Column(name = "idSpecification")
	private String idSpecification;
	@Column(name = "keys")
	private Serializable keys;

	@Column(name = "value")
	private Serializable value;
	@JsonIgnore
	@OneToMany( mappedBy = "specification")
	private List<SpecificationDetails> specificationDetailses;
}
