package com.asm.entity;
// Generated Jul 21, 2023, 11:15:56 AM by Hibernate Tools 4.3.6.Final

import jakarta.persistence.Column;
import jakarta.persistence.Embeddable;

/**
 * SpecificationDetailsId generated by hbm2java
 */
@Embeddable
public class SpecificationDetailsId implements java.io.Serializable {

	@Column(name = "idSpecificationDetails", nullable = false, length = 10)
	private String idSpecificationDetails;
	@Column(name = "idProduct", nullable = false, length = 10)
	private String idProduct;

	@Column(name = "idSpecification", nullable = false, length = 10)
	private String idSpecification;
}
