package com.asm.entity;
// Generated Jul 21, 2023, 11:15:56 AM by Hibernate Tools 4.3.6.Final

import jakarta.persistence.AttributeOverride;
import jakarta.persistence.AttributeOverrides;
import jakarta.persistence.Column;
import jakarta.persistence.EmbeddedId;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * SpecificationDetails generated by hbm2java
 */
@Entity
@Table(name = "specificationDetails", schema = "dbo", catalog = "DBAsmJv6")
public class SpecificationDetails implements java.io.Serializable {

	private SpecificationDetailsId id;
	private Product product;
	private Specification specification;

	public SpecificationDetails() {
	}

	public SpecificationDetails(SpecificationDetailsId id, Product product, Specification specification) {
		this.id = id;
		this.product = product;
		this.specification = specification;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idSpecificationDetails", column = @Column(name = "idSpecificationDetails", nullable = false, length = 10)),
			@AttributeOverride(name = "idProduct", column = @Column(name = "idProduct", nullable = false, length = 10)),
			@AttributeOverride(name = "idSpecification", column = @Column(name = "idSpecification", nullable = false, length = 10)) })
	public SpecificationDetailsId getId() {
		return this.id;
	}

	public void setId(SpecificationDetailsId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idProduct", nullable = false, insertable = false, updatable = false)
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idSpecification", nullable = false, insertable = false, updatable = false)
	public Specification getSpecification() {
		return this.specification;
	}

	public void setSpecification(Specification specification) {
		this.specification = specification;
	}

}
