package com.asm.entity;
// Generated Jul 21, 2023, 11:15:56 AM by Hibernate Tools 4.3.6.Final

import java.io.Serializable;
import java.util.HashSet;
import java.util.List;
import java.util.Set;



import com.fasterxml.jackson.annotation.JsonIgnore;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Pattern;
import jakarta.validation.constraints.Size;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Users generated by hbm2java
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
@Entity
@Table(name = "users")
public class Users {
	
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "Iduser")
	private String id;
	
//	@Email(message = "Email format is not correct")
//	@NotBlank(message = "Email cannot be blank")
	@Column(name = "email")
	private String email;
//	
//	@NotBlank( message = "Name cannot be left blank")
	@Column(name = "name")
	private String name;
	
//	@Size(min =8 ,message = "Password must be more than 8 characters")
	@Column(name = "password")
	private String password;
//	   @Pattern(regexp = "^\\d{9,12}$", message = "invalid phone number")
	@Column(name = "phone")
	private String phone;

	@Column(name = "role")
	private Boolean role;
	@JsonIgnore
	@OneToMany(mappedBy = "users", fetch = FetchType.EAGER)
	private List<Invoice> invoices;
}
